name: Check for updates

on:
  schedule:
    # Run every day at 5.00 AM UTC
    - cron: "0 5 * * *"

jobs:
  check:
    name: Check for new versions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check for new TF and TG
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          TERM: xterm-256color
        run: make update-versions

      # env.VERSION_TAG is set by 'make update-versions'

      - name: Commit and push changes (conditional)
        if: env.VERSION_TAG != 'null'
        uses: devops-infra/action-commit-push@v0.9.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: dependency/${{ env.VERSION_TAG }}
          commit_message: "Bump for ${{ env.VERSION_TAG }}"

      - name: Download Pull Request template
        if: env.VERSION_TAG != 'null'
        shell: bash
        run: |
          mkdir -p .tmp
          curl -LsS https://raw.githubusercontent.com/devops-infra/.github/master/PULL_REQUEST_TEMPLATE.md -o .tmp/PULL_REQUEST_TEMPLATE.md

      - name: Create pull request
        if: env.VERSION_TAG != 'null'
        uses: devops-infra/action-pull-request@v0.5.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: Bump for ${{ env.VERSION_TAG }}
          assignee: ${{ github.actor }}
          label: automatic,dependency
          template: .tmp/PULL_REQUEST_TEMPLATE.md
          get_diff: true
          target_branch: develop
