name: Snyk Check

on:
  schedule:
    # Run every week at 6.00 AM UTC
     - cron: "0 6 */7 * *"

jobs:
  snyk:
    name: Snyk check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.3.5

    - name: Build a full image
      run: make build-aws-azure-gcp

    - name: Run Snyk
      continue-on-error: true
      uses: snyk/actions/docker@0.3.0
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: devopsinfra/docker-terragrunt:aws-azure-gcp-latest
        args: --file=Dockerfile

    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: snyk.sarif
